version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static_data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=maischool
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - SECRET_KEY=samplesecretkey123
    depends_on:
      - db
    networks:
      - maischool_network
    
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - maischool_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=maischool
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - maischool_network
    ports:
      - "5432:5432"

volumes:
  static_data:

networks:
  maischool_network:
    driver: bridge

