# Generated by Django 3.1.3 on 2020-11-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201121_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='users',
        ),
        migrations.AddField(
            model_name='school',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
