# Generated by Django 3.1.3 on 2020-11-21 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201121_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='users',
        ),
        migrations.AddField(
            model_name='school',
            name='users',
            field=models.ManyToManyField(through='core.Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
