# Generated by Django 3.1.3 on 2020-11-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201115_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.category'),
        ),
    ]
