# Generated by Django 3.1.3 on 2020-11-16 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201116_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='users',
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.category'),
        ),
    ]
